# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='divisi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karyawan.Divisi'),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='jabatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karyawan.Jabatan'),
        ),
    ]
